# Generated by Django 4.2.3 on 2023-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(db_column='my_name', max_length=50)),
                ('_lastname', models.CharField(db_column='my_lastname', max_length=50)),
                ('_midname', models.CharField(db_column='my_midname', max_length=50)),
                ('_email', models.EmailField(db_column='my_email', max_length=254)),
                ('_phone', models.IntegerField(db_column='my_phone')),
                ('_FIO', models.CharField(db_column='my_midFIO', max_length=150)),
            ],
        ),
    ]
