# Generated by Django 4.2.3 on 2023-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0002_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='_FIO',
            new_name='FIO',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='_midname',
            new_name='midname',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='_phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
