# Generated by Django 4.2.3 on 2023-08-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0003_rename__fio_participant_fio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(db_column='participant_school')),
                ('participant_class', models.IntegerField(db_column='participant_class')),
                ('year', models.IntegerField(db_column='year')),
                ('letter', models.TextField(db_column='participant_letter')),
            ],
        ),
        migrations.CreateModel(
            name='teamMentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(db_column='mentor_FIO', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='midname',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='text',
        ),
        migrations.AlterField(
            model_name='participant',
            name='FIO',
            field=models.CharField(blank=True, db_column='my_FIO', max_length=150),
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='team_name')),
                ('members', models.ManyToManyField(through='MHT.membership', to='MHT.participant')),
                ('mentors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHT.teammentor')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHT.participant'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MHT.team'),
        ),
    ]
