# Generated by Django 4.2.3 on 2023-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0005_rename_mentors_team_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_column='team_name', max_length=200),
        ),
    ]
