# Generated by Django 4.2.3 on 2023-08-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0006_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='mentor',
        ),
        migrations.AddField(
            model_name='team',
            name='mentor',
            field=models.ManyToManyField(to='MHT.teammentor'),
        ),
    ]
