# Generated by Django 4.2.3 on 2023-08-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0007_remove_team_mentor_team_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='letter',
            field=models.TextField(blank=True, db_column='participant_letter'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(db_column='my_phone', max_length=17),
        ),
    ]
