# Generated by Django 4.2.3 on 2023-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0008_alter_membership_letter_alter_participant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='participant_class',
            field=models.IntegerField(verbose_name='participant_class'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='school',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='membership',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
