# Generated by Django 4.2.3 on 2023-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MHT', '0009_alter_membership_id_alter_membership_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(blank=True, db_column='team_region', max_length=200),
        ),
    ]
